version: '3'
services:
  postgres-1:
    image: postgres:latest
    environment:
      - POSTGRES_DB=productDB
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data1
  postgres-2:
    image: postgres:latest
    environment:
      - POSTGRES_DB=userDB
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data2

  go-product-service:
    build: ./go-service-pr9
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  go-user-service:
    build: ./go-service-pr9
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-service