version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=Marketplace1
      - POSTGRES_PASSWORD=0813526
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  go-service:
    build: ./go-service-pr9
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-service