version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=productDB
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data1

  go-product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8080

  go-user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-service